<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Operations;


class LoginApiV1TokenPostResponse
{
	
    public string $contentType;
    
    /**
     * Validation Error
     * 
     * @var ?\lk\api\Models\Shared\HTTPValidationError $httpValidationError
     */
	
    public ?\lk\api\Models\Shared\HTTPValidationError $httpValidationError = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Successful Response
     * 
     * @var mixed $loginApiV1TokenPost200ApplicationJSONAny
     */
	
    public mixed $loginApiV1TokenPost200ApplicationJSONAny = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->httpValidationError = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->loginApiV1TokenPost200ApplicationJSONAny = null;
	}
}
