<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Operations;

use \lk\api\Utils\SpeakeasyMetadata;
class StatusValidatedApiV1OrdersOrderIdStatusPostRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \lk\api\Models\Shared\OrderStatus $orderStatus;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=order_id')]
    public int $orderId;
    
	public function __construct()
	{
		$this->orderStatus = new \lk\api\Models\Shared\OrderStatus();
		$this->orderId = 0;
	}
}
