<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Operations;


class StatusSchemaApiV1OrdersStatusSchemaGetResponse
{
	
    public string $contentType;
    
    /**
     * Successful Response
     * 
     * @var ?\lk\api\Models\Shared\Response $response
     */
	
    public ?\lk\api\Models\Shared\Response $response = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->response = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
