<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Operations;

use \lk\api\Utils\SpeakeasyMetadata;
class TicketStatusApiV1TicketTicketIdCommentPostRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \lk\api\Models\Shared\OrderTicket $orderTicket;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ticket_id')]
    public string $ticketId;
    
	public function __construct()
	{
		$this->orderTicket = new \lk\api\Models\Shared\OrderTicket();
		$this->ticketId = "";
	}
}
