<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Customer - Represents info about order customer
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Customer
{
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * This field could be numeric string
     * 
     * @var int $erpId
     */
	#[\JMS\Serializer\Annotation\SerializedName('erp_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $erpId;
    
	#[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $firstName;
    
    /**
     * This field could be numeric string
     * 
     * @var int $humanId
     */
	#[\JMS\Serializer\Annotation\SerializedName('human_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $humanId;
    
    /**
     * This field could be numeric string
     * 
     * @var int $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastName;
    
	#[\JMS\Serializer\Annotation\SerializedName('middle_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $middleName;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phone;
    
	public function __construct()
	{
		$this->email = "";
		$this->erpId = 0;
		$this->firstName = "";
		$this->humanId = 0;
		$this->id = 0;
		$this->lastName = "";
		$this->middleName = "";
		$this->phone = "";
	}
}
