<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * HTTPValidationError - Validation Error
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class HTTPValidationError
{
    /**
     * $detail
     * 
     * @var ?array<\lk\api\Models\Shared\ValidationError> $detail
     */
	#[\JMS\Serializer\Annotation\SerializedName('detail')]
    #[\JMS\Serializer\Annotation\Type('array<lk\api\Models\Shared\ValidationError>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $detail = null;
    
	public function __construct()
	{
		$this->detail = null;
	}
}
