<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * NPPackStation - Represents info about shipping via `Nova Posta PackStation` method
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class NPPackStation
{
	#[\JMS\Serializer\Annotation\SerializedName('city')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $city;
    
	#[\JMS\Serializer\Annotation\SerializedName('city_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cityId;
    
	#[\JMS\Serializer\Annotation\SerializedName('comment')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $comment;
    
	#[\JMS\Serializer\Annotation\SerializedName('region')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $region;
    
	#[\JMS\Serializer\Annotation\SerializedName('region_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $regionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('settlement_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $settlementDescription;
    
	#[\JMS\Serializer\Annotation\SerializedName('settlement_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $settlementType;
    
    /**
     * Represents info about street
     * 
     * @var \lk\api\Models\Shared\Street $street
     */
	#[\JMS\Serializer\Annotation\SerializedName('street')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\Street')]
    public Street $street;
    
	#[\JMS\Serializer\Annotation\SerializedName('warehouse_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $warehouseId;
    
    /**
     * This field could be numeric string
     * 
     * @var int $warehouseNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('warehouse_number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $warehouseNumber;
    
	public function __construct()
	{
		$this->city = "";
		$this->cityId = "";
		$this->comment = "";
		$this->region = "";
		$this->regionId = "";
		$this->settlementDescription = "";
		$this->settlementType = "";
		$this->street = new \lk\api\Models\Shared\Street();
		$this->warehouseId = "";
		$this->warehouseNumber = 0;
	}
}
