<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/** An enumeration. */
enum OrderTicketStatus: string
{
    case Ae5f2f10F46b1410Fd9a0050ba5d6c38 = 'ae5f2f10-f46b-1410-fd9a-0050ba5d6c38';
    case Sevene9f1204F46b1410Fb9a0050ba5d6c38 = '7e9f1204-f46b-1410-fb9a-0050ba5d6c38';
    case Threee7f420cF46b1410Fc9a0050ba5d6c38 = '3e7f420c-f46b-1410-fc9a-0050ba5d6c38';
    case Ae7f411eF46b1410009b0050ba5d6c38 = 'ae7f411e-f46b-1410-009b-0050ba5d6c38';
    case ThreeThousandEightHundredAndFiftyNinec6e7Cbcb486bBa5377808fe6e593 = '3859c6e7-cbcb-486b-ba53-77808fe6e593';
    case Sixe5f4218F46b1410Fe9a0050ba5d6c38 = '6e5f4218-f46b-1410-fe9a-0050ba5d6c38';
}
