<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


class OrderTicket
{
    /**
     * Decision
     * 
     * @var string $decision
     */
	#[\JMS\Serializer\Annotation\SerializedName('decision')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $decision;
    
    /**
     * Marketplace Order ID
     * 
     * @var int $orderId
     */
	#[\JMS\Serializer\Annotation\SerializedName('order_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $orderId;
    
    /**
     * Format YYYY-MM-DD[T]HH:MM
     * 
     * @var \DateTime $solutionTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('solution_time')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $solutionTime;
    
    /**
     * Status
     * 
     * @var \lk\api\Models\Shared\OrderTicketStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<lk\api\Models\Shared\OrderTicketStatus>')]
    public OrderTicketStatus $status;
    
    /**
     * BPM ticket ID
     * 
     * @var string $ticketId
     */
	#[\JMS\Serializer\Annotation\SerializedName('ticket_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ticketId;
    
	public function __construct()
	{
		$this->decision = "";
		$this->orderId = 0;
		$this->solutionTime = new \DateTime();
		$this->status = \lk\api\Models\Shared\OrderTicketStatus::AE5F2F10_F46B1410_FD9A0050BA5D6C38;
		$this->ticketId = "";
	}
}
