<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Order - Represents full info about order
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Order
{
    /**
     * Format YYYY-MM-DD[T]HH:MM
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * Represents info about order customer
     * 
     * @var \lk\api\Models\Shared\Customer $customer
     */
	#[\JMS\Serializer\Annotation\SerializedName('customer')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\Customer')]
    public Customer $customer;
    
    /**
     * $items
     * 
     * @var array<\lk\api\Models\Shared\Item> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<lk\api\Models\Shared\Item>')]
    public array $items;
    
    /**
     * This field could be numeric string
     * 
     * @var int $merchantId
     */
	#[\JMS\Serializer\Annotation\SerializedName('merchant_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $merchantId;
    
    /**
     * This field could be numeric string
     * 
     * @var int $orderId
     */
	#[\JMS\Serializer\Annotation\SerializedName('order_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $orderId;
    
    /**
     * Represents info about order payment
     * 
     * @var \lk\api\Models\Shared\Payment $payment
     */
	#[\JMS\Serializer\Annotation\SerializedName('payment')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\Payment')]
    public Payment $payment;
    
    /**
     * Represents info about shipping order
     * 
     * @var \lk\api\Models\Shared\Shipping $shipping
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipping')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\Shipping')]
    public Shipping $shipping;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->customer = new \lk\api\Models\Shared\Customer();
		$this->items = [];
		$this->merchantId = 0;
		$this->orderId = 0;
		$this->payment = new \lk\api\Models\Shared\Payment();
		$this->shipping = new \lk\api\Models\Shared\Shipping();
	}
}
