<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Payment - Represents info about order payment
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Payment
{
    /**
     * This field could be numeric string
     * 
     * @var \lk\api\Models\Shared\PaymentMethod $method
     */
	#[\JMS\Serializer\Annotation\SerializedName('method')]
    #[\JMS\Serializer\Annotation\Type('enum<lk\api\Models\Shared\PaymentMethod>')]
    public PaymentMethod $method;
    
    /**
     * This field could be numeric string
     * 
     * @var \lk\api\Models\Shared\PaymentStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<lk\api\Models\Shared\PaymentStatus>')]
    public PaymentStatus $status;
    
	public function __construct()
	{
		$this->method = \lk\api\Models\Shared\PaymentMethod::Zero;
		$this->status = \lk\api\Models\Shared\PaymentStatus::Zero;
	}
}
