<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Recipient - Represents info about recipient
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Recipient
{
	#[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $firstName;
    
	#[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastName;
    
	#[\JMS\Serializer\Annotation\SerializedName('middle_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $middleName;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phone;
    
	public function __construct()
	{
		$this->firstName = "";
		$this->lastName = "";
		$this->middleName = "";
		$this->phone = "";
	}
}
