<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Response - Successful Response
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Response
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\ResponseData')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ResponseData $data = null;
    
    /**
     * $errors
     * 
     * @var ?array<string> $errors
     */
	#[\JMS\Serializer\Annotation\SerializedName('errors')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $errors = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('success')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $success;
    
	public function __construct()
	{
		$this->data = null;
		$this->errors = null;
		$this->success = false;
	}
}
