<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


/**
 * Shipping - Represents info about shipping order
 * 
 * @package lk\api\Models\Shared
 * @access public
 */
class Shipping
{
    /**
     * Represents info about shipping via `Nova Posta PackStation` method
     * 
     * @var \lk\api\Models\Shared\NPPackStation $address
     */
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\NPPackStation')]
    public NPPackStation $address;
    
	#[\JMS\Serializer\Annotation\SerializedName('method')]
    #[\JMS\Serializer\Annotation\Type('enum<lk\api\Models\Shared\ShippingMethod>')]
    public ShippingMethod $method;
    
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $price = null;
    
    /**
     * Represents info about recipient
     * 
     * @var \lk\api\Models\Shared\Recipient $recipient
     */
	#[\JMS\Serializer\Annotation\SerializedName('recipient')]
    #[\JMS\Serializer\Annotation\Type('lk\api\Models\Shared\Recipient')]
    public Recipient $recipient;
    
	public function __construct()
	{
		$this->address = new \lk\api\Models\Shared\NPPackStation();
		$this->method = \lk\api\Models\Shared\ShippingMethod::NOVAPOSHTA_PACKSTATION;
		$this->price = null;
		$this->recipient = new \lk\api\Models\Shared\Recipient();
	}
}
