<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api\Models\Shared;


enum ShippingMethod: string
{
    case NovaposhtaPackstation = 'novaposhta_packstation';
}
