<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace lk\api;

/**
 * Lk - Merchant Center API: API for EVA marketplace backoffice. <br><br> Other documentation: <br><ul><li><a href="https://eva-product.atlassian.net/wiki/spaces/EVA/pages/107020299/Marketplace">Internal project docs</a></li><li><a href="/redoc">Reference Documentation</a></li></ul><br>Request is succeeded if response code is 200 and response JSON contains `{"success": true, ...}`
 * 
 * @package lk\api
 * @access public
 */
class Lk
{
	public const SERVERS = [
		'https://api.eva-dev.pro',
	];
  	
	public Authentication $authentication;
	
	public Order $order;
	
	public OrderStatus $orderStatus;
	
	public OrderTicket $orderTicket;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return LkBuilder
	 */
	public static function builder(): LkBuilder
	{
		return new LkBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->authentication = new Authentication($this->sdkConfiguration);
		
		$this->order = new Order($this->sdkConfiguration);
		
		$this->orderStatus = new OrderStatus($this->sdkConfiguration);
		
		$this->orderTicket = new OrderTicket($this->sdkConfiguration);
	}
}